In [ ]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/My Drive/MSc_project/.MAIN

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/MSc_project/.MAIN

In [ ]:
import json
import pandas as pd
import time
from datetime import datetime
import os.path

def find_percent(df):
    percent = df['infector-friends']/df['number-of-i-informers']
    return percent.to_list()

In [ ]:
hashtags = ['avengers','blm','borisjohnson','brexit','climatechange','covid','gaza','loveisland','monkeypox','nhs','olivianewtonjohn','supercup','UkraineWar']
# hashtags = ['UkraineWar']

results = {}

for hashtag in hashtags:

    path = f'{hashtag}{os.path.sep}updated_informers_data.json'
    with open(path) as jf:
        data = json.load(jf)

    df = pd.DataFrame.from_dict(data,orient='index')
    max_infrmr = df['num-informers'].max()

    info = {}

    for i in range(max_infrmr+1):
        db = df.loc[df['num-informers']==i]
        n = len(db) # the number of tweets with i informers
        if n != 0:
            num_infector_friends = db['infector-is-friend'].sum()
            # percentage = num_infector_friends/n
            # # print(percentage)
            info.update( {i : [ num_infector_friends, n] } )
        else:
            info.update( {i : [ None, None ] } )
    print(f'done {hashtag}')

    breakdown = pd.DataFrame.from_dict(info,orient='index', columns = ['infector-friends','number-of-informers'])
    n = len(breakdown)

    info = pd.DataFrame(breakdown.iloc[0:50])

    info.loc[len(info)+1] = breakdown.iloc[50:75].sum()

    save_path = f'informer_results{os.path.sep}infector_breakdown{os.path.sep}{hashtag}_breakdown.csv'

    if n>100:
        info.loc[len(info)+1] =  breakdown.iloc[75:100].sum() 
    else:
        info.loc[len(info)+1] =  breakdown.iloc[75:n].sum() 
        info.to_csv(save_path)
        results.update( {hashtag:find_percent(info) } )
        pass

    if n>150:
        info.loc[len(info)+1] =  breakdown.iloc[100:150].sum() 
    else: 
        info.loc[len(info)+1] =  breakdown.iloc[100:n].sum()
        info.to_csv(save_path)
        results.update( {hashtag:find_percent(info) } )
        pass

    if n>250:
        info.loc[len(info)+1] =  breakdown.iloc[150:250].sum() 
    else:
        info.loc[len(info)+1] =  breakdown.iloc[150:250].sum() 
        info.to_csv(save_path)
        results.update( {hashtag:find_percent(info) } )
        pass

    if n>500:
        info.loc[len(info)+1] =  breakdown.iloc[250:500].sum() 
        info.to_csv(save_path)
        results.update( {hashtag:find_percent(info) } )
    else:
        info.loc[len(info)+1] =  breakdown.iloc[250:n].sum() 
        info.to_csv(save_path)
        results.update( {hashtag:find_percent(info) } )

done avengers
done blm
done borisjohnson
done brexit
done climatechange
done covid
done gaza
done loveisland
done monkeypox
done nhs
done olivianewtonjohn
done supercup
done UkraineWar

In [ ]:
hashtags = ['avengers','blm','borisjohnson','brexit','climatechange','covid','gaza','loveisland','monkeypox','nhs','olivianewtonjohn','supercup','UkraineWar']
# hashtags = ['UkraineWar']

results = {}

for hashtag in hashtags:

    path = f'{hashtag}{os.path.sep}updated_informers_data.json'
    with open(path) as jf:
        data = json.load(jf)

    df = pd.DataFrame.from_dict(data,orient='index')
    max_infrmr = df['num-informers'].max()

    info = {}

    for i in range(max_infrmr+1):
        db = df.loc[df['num-informers']==i]
        n = len(db) # the number of tweets with i informers
        if n != 0:
            num_infector_friends = db['infector-is-friend'].sum()
            info.update( {i : [ num_infector_friends, n] } )
        else:
            info.update( {i : [ None, None ] } )

    breakdown = pd.DataFrame.from_dict(info,orient='index', columns = ['infector-friends','number-of-i-informers'])
    n = len(breakdown)

    info = pd.DataFrame(breakdown.iloc[1:10].sum()).T

    for counter in range(n+1):
        if (counter%10==0):
            info.loc[len(info)+1] = breakdown.iloc[counter:counter+10].sum().to_list() 

    # add on the info that was not added on the end
    info.loc[len(info)+1] = breakdown.iloc[counter:].sum().to_list() 

    # info.loc[len(info)+1] = breakdown.iloc[10:20].sum().to_list() 
    # info.loc[len(info)+1] = breakdown.iloc[20:40].sum().to_list() 
    # info.loc[len(info)+1] = breakdown.iloc[40:80].sum().to_list() 
    # info.loc[len(info)+1] = breakdown.iloc[80:].sum().to_list() 

    results.update( {hashtag:find_percent(info) } )
    print(f'done {hashtag}')

done avengers
done blm
done borisjohnson
done brexit
done climatechange
done covid
done gaza
done loveisland
done monkeypox
done nhs
done olivianewtonjohn
done supercup
done UkraineWar

In [ ]:
# df = pd.DataFrame.from_dict(results,orient='columns')

df = pd.DataFrame( dict( [(key,pd.Series(v)) for key,v in results.items() ] ) )

df.to_csv(f'informer_results{os.path.sep}infector_breakdown{os.path.sep}all_breakdown_ranges.csv')

In [ ]:
df

,avengers,blm,borisjohnson,brexit,climatechange,covid,gaza,loveisland,monkeypox,nhs,olivianewtonjohn,supercup,UkraineWar
0,0.595609,0.702770,0.485306,0.356815,0.607434,0.414881,0.468281,0.220510,0.647295,0.334006,0.523840,0.601751,0.583531
1,0.595609,0.702770,0.485306,0.356815,0.607434,0.414881,0.468281,0.220510,0.647295,0.334006,0.523840,0.601751,0.583531
2,0.572368,0.694282,0.429199,0.428256,0.600000,0.592657,0.658654,0.305838,0.665335,0.433031,0.498551,0.599284,0.746055
3,0.507246,0.713555,0.488496,0.467257,0.533040,0.617021,0.569231,0.389140,0.614035,0.480715,0.627451,0.629808,0.762162
4,0.585859,0.711191,0.471154,0.513021,0.730000,0.596330,0.588235,0.500000,0.645260,0.484848,0.567568,0.593750,0.780488
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
results

{'UkraineWar': [nan,
  nan,
  1.0,
  nan,
  nan,
  nan,
  nan,
  nan,
  1.0,
  nan,
  nan,
  1.0,
  nan,
  nan,
  nan,
  nan,
  0.3333333333333333,
  nan,
  1.0,
  nan,
  nan,
  0.5,
  0.0,
  nan,
  nan,
  1.0,
  nan,
  nan,
  1.0,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  0.0,
  nan,
  nan,
  nan,
  nan,
  0.0,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  0.0,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  0.0,
  nan,
  nan,
  0.0]}